#!/bin/bash

echo "=== API ROUTES FIX PLAN ==="
echo ""

echo "1. BACKUP CURRENT ROUTES..."
cp -r api/routes api/routes_backup_$(date +%Y%m%d_%H%M%S)
echo "   ✅ Routes backed up"

echo ""
echo "2. IDENTIFYING DUPLICATE ROUTE FILES..."
echo "   Duplicate files found:"
echo "   - articles.py (has duplicates)"
echo "   - story_consolidation.py (has duplicates)"
echo "   - rss_processing.py (has duplicates)"
echo "   - automation.py (has duplicates)"
echo "   - metrics_visualization.py (has duplicates)"
echo "   - ml_queue.py (has duplicates)"
echo "   - ai_processing.py (has duplicates)"
echo "   - rss.py (has duplicates)"
echo "   - digest.py (has duplicates)"
echo "   - story_management.py (has duplicates)"
echo "   - sources.py (has duplicates)"
echo "   - monitoring.py (has duplicates)"
echo "   - search.py (has duplicates)"
echo "   - health.py (has duplicates)"
echo "   - rag.py (has duplicates)"
echo "   - entities.py (has duplicates)"
echo "   - clusters.py (has duplicates)"

echo ""
echo "3. RECOMMENDED ACTIONS:"
echo "   a) Remove duplicate route definitions from each file"
echo "   b) Add proper response_model to all endpoints"
echo "   c) Ensure consistent error handling"
echo "   d) Add proper validation schemas"
echo "   e) Update main.py to include only necessary routes"
echo "   f) Test all endpoints for functionality"

echo ""
echo "4. ESTIMATED TIME TO FIX:"
echo "   - Remove duplicates: 2-3 hours"
echo "   - Add response models: 3-4 hours"
echo "   - Schema alignment: 2-3 hours"
echo "   - Testing: 2-3 hours"
echo "   - Total: 9-13 hours"

echo ""
echo "=== API FIX PLAN COMPLETED ==="
