#!/usr/bin/env python3
"""
Verify that extracted events connect to domain storylines and that entity-based
chains are populated (story_entity_index, storyline_articles ↔ article_entities).

Read-only. From repo root:
  PYTHONPATH=api uv run python scripts/verify_storyline_event_entity_chains.py
  PYTHONPATH=api uv run python scripts/verify_storyline_event_entity_chains.py --write-report docs/generated/STORYLINE_EVENT_ENTITY_CHAINS_REPORT.md

Pipeline context (v5/v8):
- **New storylines**: AI clustering (`storyline_discovery`), `storyline_automation` (match articles
  to storylines), etc.
- **Event → storyline**: `story_continuation` matches **unlinked** `public.chronological_events`
  to existing domain `storylines` using `story_entity_index` (≥2 overlapping entity names)
  + event-type compatibility + LLM verification, then sets `chronological_events.storyline_id`.
- **Entity index**: populated when events link (`update_entity_index`) and when articles are
  added to storylines (`storyline_automation_service` merges `article_entities`).
"""
from __future__ import annotations

import argparse
import os
import sys
from datetime import datetime, timezone

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
for p in (ROOT, os.path.join(ROOT, "api")):
    if p not in sys.path:
        sys.path.insert(0, p)

try:
    from dotenv import load_dotenv

    load_dotenv(os.path.join(ROOT, "api", ".env"), override=False)
    load_dotenv(os.path.join(ROOT, ".env"), override=False)
except ImportError:
    pass

if not os.environ.get("DB_PASSWORD") and os.path.exists(os.path.join(ROOT, ".db_password_widow")):
    try:
        with open(os.path.join(ROOT, ".db_password_widow")) as f:
            os.environ.setdefault("DB_PASSWORD", f.read().strip())
    except OSError:
        pass

SCHEMAS = ("politics", "finance", "science_tech")


def _has_table(cur, schema: str, table: str) -> bool:
    cur.execute(
        """
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = %s AND table_name = %s
        """,
        (schema, table),
    )
    return cur.fetchone() is not None


def _count_story_entity_index(cur, sch: str) -> tuple[int, str]:
    """
    Prefer `{schema}.story_entity_index`; if missing, use `public.story_entity_index`
    rows whose `storyline_id` exists in `{schema}.storylines`.
    If the table exists nowhere, return 0 with a warning label.
    """
    if _has_table(cur, sch, "story_entity_index"):
        cur.execute(f"SELECT COUNT(*) FROM {sch}.story_entity_index")
        return cur.fetchone()[0], f"{sch}.story_entity_index"
    if _has_table(cur, "public", "story_entity_index"):
        cur.execute(
            f"""
            SELECT COUNT(*) FROM public.story_entity_index sei
            INNER JOIN {sch}.storylines s ON s.id = sei.storyline_id
            """
        )
        return cur.fetchone()[0], "public.story_entity_index → joined to " + sch + ".storylines"
    return 0, "story_entity_index missing (apply migration 135 / storyline continuation needs this)"


def _emit(lines: list[str], path: str | None) -> None:
    text = "\n".join(lines) + "\n"
    print(text.rstrip())
    if path:
        parent = os.path.dirname(path)
        if parent:
            os.makedirs(parent, exist_ok=True)
        preamble = (
            "<!-- Auto-generated by scripts/verify_storyline_event_entity_chains.py -->\n\n"
        )
        with open(path, "w", encoding="utf-8") as f:
            f.write(preamble)
            f.write(text)


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument(
        "--write-report",
        metavar="PATH",
        help="Write markdown report (e.g. docs/generated/STORYLINE_EVENT_ENTITY_CHAINS_REPORT.md)",
    )
    args = p.parse_args()

    from shared.database.connection import get_db_connection

    conn = get_db_connection()
    if not conn:
        print("ERROR: no database connection")
        return 1

    lines: list[str] = []
    now = datetime.now(timezone.utc).isoformat()
    lines.append(f"# Storyline ↔ events ↔ entities (verification) ({now})")
    lines.append("")
    lines.append("## Domain storylines & entity index")
    lines.append("")
    lines.append("| Schema | `storylines` | `storyline_articles` | `story_entity_index` (see note) |")
    lines.append("|--------|--------------|------------------------|----------------------------------|")

    cur = conn.cursor()
    ok = False
    try:
        for sch in SCHEMAS:
            cur.execute(
                f"""
                SELECT
                  (SELECT COUNT(*) FROM {sch}.storylines),
                  (SELECT COUNT(*) FROM {sch}.storyline_articles)
                """
            )
            r = cur.fetchone()
            sei_n, sei_src = _count_story_entity_index(cur, sch)
            lines.append(f"| `{sch}` | {r[0]:,} | {r[1]:,} | {sei_n:,} (`{sei_src}`) |")

        lines.append("")
        lines.append(
            "> **Note:** If `story_entity_index` lives only in `public`, counts are rows whose "
            "`storyline_id` matches a storyline in that domain."
        )

        lines.append("")
        lines.append("## `public.chronological_events` vs domain articles")
        lines.append("")
        lines.append(
            "Events are global; `source_article_id` is resolved per domain by joining to that "
            "schema's `articles` (IDs are per-schema)."
        )
        lines.append("")
        lines.append("| Schema | events tied to this domain's articles | with non-empty `storyline_id` |")
        lines.append("|--------|----------------------------------------|--------------------------------|")

        domain_event_stats = []
        for sch in SCHEMAS:
            cur.execute(
                f"""
                SELECT COUNT(*) FROM public.chronological_events ce
                INNER JOIN {sch}.articles a ON a.id = ce.source_article_id
                """
            )
            total_dom = cur.fetchone()[0]
            cur.execute(
                f"""
                SELECT COUNT(*) FROM public.chronological_events ce
                INNER JOIN {sch}.articles a ON a.id = ce.source_article_id
                WHERE ce.storyline_id IS NOT NULL AND trim(ce.storyline_id) <> ''
                """
            )
            linked_dom = cur.fetchone()[0]
            domain_event_stats.append((sch, total_dom, linked_dom))
            lines.append(f"| `{sch}` | {total_dom:,} | {linked_dom:,} |")

        lines.append("")
        lines.append("## Event → storyline integrity (numeric `storyline_id` → domain `storylines`)")
        lines.append("")
        lines.append(
            "For events whose `storyline_id` is numeric, verify a matching row exists in the "
            "same domain as `source_article_id`."
        )
        lines.append("")
        lines.append("| Schema | events with numeric `storyline_id` | matching `storylines.id` | orphan (no row) |")
        lines.append("|--------|--------------------------------------|---------------------------|-----------------|")

        orphans_total = 0
        for sch in SCHEMAS:
            cur.execute(
                f"""
                SELECT COUNT(*) FROM public.chronological_events ce
                INNER JOIN {sch}.articles a ON a.id = ce.source_article_id
                WHERE trim(ce.storyline_id) <> ''
                  AND ce.storyline_id ~ '^[0-9]+$'
                """
            )
            num_story = cur.fetchone()[0]
            cur.execute(
                f"""
                SELECT COUNT(*) FROM public.chronological_events ce
                INNER JOIN {sch}.articles a ON a.id = ce.source_article_id
                INNER JOIN {sch}.storylines s ON s.id = ce.storyline_id::integer
                WHERE trim(ce.storyline_id) <> ''
                  AND ce.storyline_id ~ '^[0-9]+$'
                """
            )
            matched = cur.fetchone()[0]
            orphan = num_story - matched
            orphans_total += orphan
            lines.append(f"| `{sch}` | {num_story:,} | {matched:,} | {orphan:,} |")

        lines.append("")
        lines.append("## Storylines with multiple linked events (event chains)")
        lines.append("")
        cur.execute(
            """
            WITH ev AS (
              SELECT ce.storyline_id::bigint AS sid, COUNT(*) AS n
              FROM public.chronological_events ce
              WHERE trim(ce.storyline_id) <> ''
                AND ce.storyline_id ~ '^[0-9]+$'
              GROUP BY ce.storyline_id::bigint
              HAVING COUNT(*) >= 2
            )
            SELECT COUNT(*) FROM ev
            """
        )
        multi_storylines = cur.fetchone()[0]
        lines.append(
            f"- Storylines (global numeric id) with **≥2** extracted events: **{multi_storylines:,}**"
        )

        cur.execute(
            """
            SELECT ce.storyline_id::bigint, COUNT(*) AS n
            FROM public.chronological_events ce
            WHERE trim(ce.storyline_id) <> ''
              AND ce.storyline_id ~ '^[0-9]+$'
            GROUP BY ce.storyline_id::bigint
            ORDER BY n DESC
            LIMIT 12
            """
        )
        top = cur.fetchall()
        if top:
            lines.append("")
            lines.append("| `storyline_id` (numeric) | event count |")
            lines.append("|--------------------------|-------------|")
            for sid, n in top:
                lines.append(f"| {sid} | {n} |")

        lines.append("")
        lines.append("## Entity overlap: storylines with articles + entities")
        lines.append("")
        lines.append(
            "Sample check: storylines that have both `storyline_articles` and `article_entities` "
            "on those articles (feeds continuation / discovery)."
        )
        lines.append("")
        lines.append("| Schema | storylines with ≥1 SA row & ≥1 entity on those articles |")
        lines.append("|--------|-----------------------------------------------------------|")

        for sch in SCHEMAS:
            cur.execute(
                f"""
                SELECT COUNT(DISTINCT sa.storyline_id)
                FROM {sch}.storyline_articles sa
                INNER JOIN {sch}.article_entities ae ON ae.article_id = sa.article_id
                """
            )
            overlap = cur.fetchone()[0]
            lines.append(f"| `{sch}` | {overlap:,} |")

        lines.append("")
        lines.append("## Interpretation")
        lines.append("")
        lines.append(
            "- **Linked events** depend on `story_continuation` finding ≥2 entity overlaps in "
            "`story_entity_index` for an existing storyline — cold events stay unlinked until "
            "storylines are seeded (discovery/automation) and indexed."
        )
        lines.append(
            "- **Orphans** (numeric `storyline_id` with no `storylines` row) usually mean "
            "deleted storylines or ID/schema mismatch; investigate if non-zero."
        )
        lines.append("")

        ok = orphans_total == 0
        lines.append(
            f"**Result:** {'OK — no orphan event→storyline references.' if ok else 'REVIEW — orphan storyline references detected.'}"
        )
        lines.append("")

    finally:
        cur.close()
        conn.close()

    out_path = None
    if args.write_report:
        out_path = args.write_report if os.path.isabs(args.write_report) else os.path.join(ROOT, args.write_report)
    _emit(lines, out_path)
    if out_path:
        print(f"\nWrote {out_path}")
    return 0 if ok else 2


if __name__ == "__main__":
    raise SystemExit(main())
