#!/usr/bin/env python3
"""
Verify that "less noticeable" intelligence phases are actually producing data.

Checks automation_run_history (are they running?) + output tables (are they writing?).

From repo root:
  PYTHONPATH=api uv run python scripts/verify_intelligence_phases_productivity.py
  PYTHONPATH=api uv run python scripts/verify_intelligence_phases_productivity.py --write-report docs/INTELLIGENCE_PHASES_PRODUCTIVITY_REPORT.md
"""
from __future__ import annotations

import argparse
import os
import sys
from datetime import datetime, timezone, timedelta

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
for p in (ROOT, os.path.join(ROOT, "api")):
    if p not in sys.path:
        sys.path.insert(0, p)

try:
    from dotenv import load_dotenv

    load_dotenv(os.path.join(ROOT, "api", ".env"), override=False)
    load_dotenv(os.path.join(ROOT, ".env"), override=False)
except ImportError:
    pass

if not os.environ.get("DB_PASSWORD") and os.path.exists(os.path.join(ROOT, ".db_password_widow")):
    try:
        with open(os.path.join(ROOT, ".db_password_widow")) as f:
            os.environ.setdefault("DB_PASSWORD", f.read().strip())
    except OSError:
        pass

PHASES = {
    "cross_domain_synthesis": {
        "output_table": "intelligence.cross_domain_correlations",
        "output_columns": ["correlation_id", "domain_1", "domain_2", "correlation_strength"],
        "recent_column": "discovered_at",
    },
    "entity_enrichment": {
        "output_table": "intelligence.entity_profiles",
        "output_columns": ["sections", "updated_at"],
        "recent_column": "updated_at",
        "filter": "sections IS NOT NULL AND sections::text != '[]' AND sections::text != '{}'",
    },
    "claims_to_facts": {
        "output_table": "intelligence.versioned_facts",
        "output_columns": ["id", "entity_profile_id", "fact_type", "extraction_method"],
        "recent_column": "created_at",
        "filter": "extraction_method != 'wikipedia'",  # entity_enrichment also writes here
    },
    "pattern_recognition": {
        "output_table": "intelligence.pattern_discoveries",
        "output_columns": ["id", "pattern_type", "domain_key", "confidence"],
        "recent_column": "created_at",
    },
    "event_coherence_review": {
        "output_table": "intelligence.tracked_events",
        "output_columns": ["id", "context_ids"],
        "recent_column": "updated_at",
        "note": "Removes contexts; hard to measure directly — check automation runs + context_ids array lengths",
    },
    "pattern_matching": {
        "output_table": "intelligence.pattern_matches",
        "output_columns": ["id", "watchlist_id", "alert_created"],
        "recent_column": "created_at",
    },
}


def _emit(lines: list[str], path: str | None) -> None:
    text = "\n".join(lines) + "\n"
    print(text.rstrip())
    if path:
        parent = os.path.dirname(path)
        if parent:
            os.makedirs(parent, exist_ok=True)
        preamble = (
            "<!-- Auto-generated by scripts/verify_intelligence_phases_productivity.py -->\n\n"
        )
        with open(path, "w", encoding="utf-8") as f:
            f.write(preamble)
            f.write(text)


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument(
        "--write-report",
        metavar="PATH",
        help="Write markdown report (e.g. docs/INTELLIGENCE_PHASES_PRODUCTIVITY_REPORT.md)",
    )
    p.add_argument("--hours", type=int, default=48, help="Window for recent activity (default: 48)")
    args = p.parse_args()

    from shared.database.connection import get_db_connection

    conn = get_db_connection()
    if not conn:
        print("ERROR: no database connection")
        return 1

    lines: list[str] = []
    now = datetime.now(timezone.utc)
    since = now - timedelta(hours=args.hours)
    cutoff_str = since.isoformat()

    lines.append(f"# Intelligence phases productivity ({now.isoformat()})")
    lines.append("")
    lines.append(f"Window: last **{args.hours} hours** (since {cutoff_str})")
    lines.append("")

    cur = conn.cursor()
    ok = True
    try:
        lines.append("## Automation run history (are phases executing?)")
        lines.append("")
        lines.append("| Phase | Runs (48h) | Success | Failed | Last run |")
        lines.append("|-------|------------|---------|--------|----------|")

        for phase_name in PHASES.keys():
            cur.execute(
                """
                SELECT COUNT(*), COUNT(*) FILTER (WHERE success), COUNT(*) FILTER (WHERE NOT success),
                       MAX(finished_at)
                FROM public.automation_run_history
                WHERE phase_name = %s AND finished_at >= %s
                """,
                (phase_name, since),
            )
            r = cur.fetchone()
            total, ok_count, fail_count, last = r[0], r[1], r[2], r[3]
            last_str = last.isoformat() if last else "never"
            lines.append(f"| `{phase_name}` | {total} | {ok_count} | {fail_count} | {last_str} |")

        lines.append("")
        lines.append("## Output tables (are phases writing data?)")
        lines.append("")

        for phase_name, info in PHASES.items():
            table = info["output_table"]
            recent_col = info.get("recent_column", "created_at")
            filter_clause = f"WHERE {info['filter']} AND" if info.get("filter") else "WHERE"

            lines.append(f"### `{phase_name}`")
            lines.append("")
            lines.append(f"**Output:** `{table}`")
            if info.get("note"):
                lines.append(f"*Note: {info['note']}*")
            lines.append("")

            try:
                cur.execute(
                    f"""
                    SELECT COUNT(*) FROM {table}
                    """
                )
                total_rows = cur.fetchone()[0]

                where_base = filter_clause if info.get("filter") else "WHERE"
                cur.execute(
                    f"""
                    SELECT COUNT(*) FROM {table}
                    {where_base} {recent_col} >= %s
                    """,
                    (since,),
                )
                recent_rows = cur.fetchone()[0]

                max_where = ""
                if info.get("filter"):
                    max_where = f"WHERE {info['filter']}"
                cur.execute(
                    f"""
                    SELECT MAX({recent_col}) FROM {table}
                    {max_where}
                    """
                )
                max_ts = cur.fetchone()[0]
                max_str = max_ts.isoformat() if max_ts else "never"

                status = "✅" if recent_rows > 0 else ("⚠️" if total_rows > 0 else "❌")
                lines.append(f"- **Status:** {status}")
                lines.append(f"- **Total rows:** {total_rows:,}")
                lines.append(f"- **Rows in last {args.hours}h:** {recent_rows:,}")
                lines.append(f"- **Most recent:** {max_str}")
                lines.append("")

                if total_rows == 0 and phase_name in ("pattern_recognition", "pattern_matching"):
                    lines.append(
                        f"  > ⚠️ **No rows** — table may be empty or phase hasn't produced output yet."
                    )
                    lines.append("")
                elif recent_rows == 0 and total_rows > 0:
                    lines.append(
                        f"  > ⚠️ **No recent activity** — phase may be idle or only processing when conditions are met."
                    )
                    lines.append("")

            except Exception as e:
                conn.rollback()
                lines.append(f"  ❌ **Error querying table:** {e}")
                lines.append("")
                ok = False

        lines.append("## Cross-checks")
        lines.append("")

        # versioned_facts: both claims_to_facts AND entity_enrichment write here
        try:
            cur.execute(
                """
                SELECT COUNT(*) FROM intelligence.versioned_facts
                WHERE created_at >= %s AND extraction_method = 'claim_extraction'
                """,
                (since,),
            )
            from_claims = cur.fetchone()[0]
            cur.execute(
                """
                SELECT COUNT(*) FROM intelligence.versioned_facts
                WHERE created_at >= %s AND extraction_method = 'wikipedia'
                """,
                (since,),
            )
            from_wiki = cur.fetchone()[0]
            lines.append(
                f"- **`versioned_facts`** (last {args.hours}h): {from_claims} from `claims_to_facts`, {from_wiki} from `entity_enrichment`"
            )
        except Exception as e:
            conn.rollback()
            lines.append(f"- **`versioned_facts` breakdown:** error — {e}")

        # pattern_matches with alerts
        try:
            cur.execute(
                """
                SELECT COUNT(*) FROM intelligence.pattern_matches
                WHERE created_at >= %s AND alert_created = TRUE
                """,
                (since,),
            )
            with_alerts = cur.fetchone()[0]
            lines.append(
                f"- **`pattern_matches` with alerts created:** {with_alerts} (last {args.hours}h)"
            )
        except Exception as e:
            conn.rollback()
            lines.append(f"- **`pattern_matches` alerts:** error — {e}")

        lines.append("")
        lines.append("## Interpretation")
        lines.append("")
        lines.append(
            "- **✅ = productive:** Phase is running and writing data in the window."
        )
        lines.append(
            "- **⚠️ = idle or conditional:** Phase runs but produced no output recently (may require specific conditions, thresholds, or backlog)."
        )
        lines.append(
            "- **❌ = no data ever:** Table is empty — phase may not have run successfully or output format changed."
        )
        lines.append("")
        lines.append(
            "**Note:** Some phases are **conditional** (e.g. `event_coherence_review` only when contexts change, "
            "`pattern_matching` only when watchlists exist). Check automation_run_history success rate to confirm "
            "they're executing even if output is sparse."
        )
        lines.append("")
        lines.append("**Claims → facts:** If `versioned_facts` stays empty while `claims_to_facts` succeeds, see "
                     "[CLAIMS_TO_FACTS_ENTITY_RESOLUTION.md](CLAIMS_TO_FACTS_ENTITY_RESOLUTION.md) and "
                     "`scripts/diagnose_claims_to_facts.py`.")
        lines.append("")

    finally:
        cur.close()
        conn.close()

    out_path = None
    if args.write_report:
        out_path = args.write_report if os.path.isabs(args.write_report) else os.path.join(ROOT, args.write_report)
    _emit(lines, out_path)
    if out_path:
        print(f"\nWrote {out_path}")
    return 0 if ok else 2


if __name__ == "__main__":
    raise SystemExit(main())
