import React, { useState, useEffect } from 'react';
import {
  Box,
  Typography,
  Button,
  Chip,
  List,
  ListItem,
  ListItemText,
  ListItemIcon,
  ListItemSecondaryAction,
  IconButton,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  TextField,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  Alert,
  CircularProgress,
  Divider,
  Badge,
  Tooltip,
  Accordion,
  AccordionSummary,
  AccordionDetails,
  InputAdornment
} from '@mui/material';
import {
  Add as AddIcon,
  Edit as EditIcon,
  Delete as DeleteIcon,
  Build as BuildIcon,
  AutoAwesome as AutoAwesomeIcon,
  Timeline as TimelineIcon,
  Notifications as NotificationsIcon,
  TrendingUp as TrendingUpIcon,
  Psychology as PsychologyIcon,
  ExpandMore as ExpandMoreIcon,
  Visibility as ViewIcon,
  Refresh as RefreshIcon,
  Search as SearchIcon
} from '@mui/icons-material';
import StoryThreadManager from '../../components/ContentPrioritization/StoryThreadManager';
import { newsSystemService } from '../../services/newsSystemService';

const UnifiedStoryDossiers = () => {
  const [storyThreads, setStoryThreads] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [filterStatus, setFilterStatus] = useState('');
  const [selectedThread, setSelectedThread] = useState(null);
  const [showThreadDialog, setShowThreadDialog] = useState(false);
  const [showCreateDialog, setShowCreateDialog] = useState(false);

  useEffect(() => {
    loadStoryThreads();
  }, []);

  const loadStoryThreads = async () => {
    setLoading(true);
    try {
      const response = await newsSystemService.getStoryThreads();
      if (response.success) {
        setStoryThreads(response.data || []);
      }
    } catch (error) {
      setError('Error loading story threads: ' + error.message);
    } finally {
      setLoading(false);
    }
  };

  const handleThreadClick = (thread) => {
    setSelectedThread(thread);
    setShowThreadDialog(true);
  };

  const handleCloseDialog = () => {
    setShowThreadDialog(false);
    setSelectedThread(null);
  };

  const handleCreateThread = () => {
    setShowCreateDialog(true);
  };

  const handleCloseCreateDialog = () => {
    setShowCreateDialog(false);
  };

  const handleDeleteThread = async (threadId) => {
    if (window.confirm('Are you sure you want to delete this story thread?')) {
      try {
        const response = await newsSystemService.deleteStoryThread(threadId);
        if (response.success) {
          setStoryThreads(prev => prev.filter(thread => thread.id !== threadId));
        } else {
          setError('Failed to delete story thread');
        }
      } catch (error) {
        setError('Error deleting story thread: ' + error.message);
      }
    }
  };

  const getFilteredThreads = () => {
    let filtered = storyThreads;

    if (searchQuery) {
      const query = searchQuery.toLowerCase();
      filtered = filtered.filter(thread =>
        thread.title?.toLowerCase().includes(query) ||
        thread.description?.toLowerCase().includes(query) ||
        thread.keywords?.some(keyword => keyword.toLowerCase().includes(query))
      );
    }

    if (filterStatus) {
      filtered = filtered.filter(thread => thread.status === filterStatus);
    }

    return filtered.sort((a, b) => new Date(b.updated_at) - new Date(a.updated_at));
  };

  const getThreadStats = () => {
    const total = storyThreads.length;
    const active = storyThreads.filter(t => t.status === 'active').length;
    const alerts = storyThreads.filter(t => t.alert_count > 0).length;
    const autoGenerated = storyThreads.filter(t => t.auto_generated).length;

    return { total, active, alerts, autoGenerated };
  };

  const renderThreadCard = (thread) => (
    <div key={thread.id} className="unified-content-card unified-fade-in">
      <div className="unified-content-header">
        <TimelineIcon sx={{ mr: 1 }} />
        <div className="unified-content-title">{thread.title}</div>
        <Box display="flex" gap={1} ml="auto">
          {thread.status === 'active' && (
            <Chip label="Active" size="small" color="success" variant="outlined" />
          )}
          {thread.alert_count > 0 && (
            <Badge badgeContent={thread.alert_count} color="error">
              <NotificationsIcon color="warning" />
            </Badge>
          )}
          {thread.auto_generated && (
            <Chip label="Auto" size="small" color="info" variant="outlined" />
          )}
        </Box>
      </div>
      <div className="unified-content-body">
        <div className="unified-content-text">
          {thread.description || 'No description available'}
        </div>
        
        {thread.keywords && thread.keywords.length > 0 && (
          <Box display="flex" gap={1} flexWrap="wrap" mt={2}>
            {thread.keywords.slice(0, 5).map((keyword, index) => (
              <Chip key={index} label={keyword} size="small" variant="outlined" />
            ))}
            {thread.keywords.length > 5 && (
              <Chip label={`+${thread.keywords.length - 5} more`} size="small" variant="outlined" />
            )}
          </Box>
        )}

        <div className="unified-content-actions">
          <Button
            variant="contained"
            size="small"
            startIcon={<ViewIcon />}
            onClick={() => handleThreadClick(thread)}
            className="unified-button-sm"
          >
            View Details
          </Button>
          <Button
            variant="outlined"
            size="small"
            startIcon={<EditIcon />}
            onClick={() => handleThreadClick(thread)}
            className="unified-button-sm"
          >
            Edit
          </Button>
          <Button
            variant="outlined"
            size="small"
            startIcon={<DeleteIcon />}
            onClick={() => handleDeleteThread(thread.id)}
            color="error"
            className="unified-button-sm"
          >
            Delete
          </Button>
        </div>

        <Box display="flex" justifyContent="space-between" mt={2} pt={2} borderTop="1px solid #f0f0f0">
          <Typography variant="caption" color="text.secondary">
            Created: {new Date(thread.created_at).toLocaleDateString()}
          </Typography>
          <Typography variant="caption" color="text.secondary">
            Updated: {new Date(thread.updated_at).toLocaleDateString()}
          </Typography>
        </Box>
      </div>
    </div>
  );

  const stats = getThreadStats();
  const filteredThreads = getFilteredThreads();

  return (
    <div className="unified-container">
      {/* Header */}
      <div className="unified-section">
        <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 3 }}>
          <Typography variant="h4" component="h1">
            Story Dossiers
          </Typography>
          <Box display="flex" gap={1}>
            <Button
              variant="contained"
              startIcon={<AddIcon />}
              onClick={handleCreateThread}
              className="unified-button"
            >
              Create Story Thread
            </Button>
            <Tooltip title="Refresh Story Threads">
              <IconButton onClick={loadStoryThreads} color="primary">
                <RefreshIcon />
              </IconButton>
            </Tooltip>
          </Box>
        </Box>

        {error && (
          <Alert severity="error" sx={{ mb: 2 }} onClose={() => setError(null)}>
            {error}
          </Alert>
        )}

        {loading && <CircularProgress sx={{ mb: 2 }} />}
      </div>

      {/* Statistics */}
      <div className="unified-section">
        <div className="unified-grid unified-grid-4">
          <div className="unified-stat-card unified-fade-in">
            <div className="unified-stat-card-content">
              <TimelineIcon sx={{ fontSize: 40 }} className="unified-stat-icon" />
              <div className="unified-stat-number" style={{ color: '#1976d2' }}>
                {stats.total}
              </div>
              <div className="unified-stat-label">Total Threads</div>
            </div>
          </div>

          <div className="unified-stat-card unified-fade-in">
            <div className="unified-stat-card-content">
              <AutoAwesome sx={{ fontSize: 40 }} className="unified-stat-icon" />
              <div className="unified-stat-number" style={{ color: '#2e7d32' }}>
                {stats.active}
              </div>
              <div className="unified-stat-label">Active Threads</div>
            </div>
          </div>

          <div className="unified-stat-card unified-fade-in">
            <div className="unified-stat-card-content">
              <NotificationsIcon sx={{ fontSize: 40 }} className="unified-stat-icon" />
              <div className="unified-stat-number" style={{ color: '#f57c00' }}>
                {stats.alerts}
              </div>
              <div className="unified-stat-label">With Alerts</div>
            </div>
          </div>

          <div className="unified-stat-card unified-fade-in">
            <div className="unified-stat-card-content">
              <PsychologyIcon sx={{ fontSize: 40 }} className="unified-stat-icon" />
              <div className="unified-stat-number" style={{ color: '#9c27b0' }}>
                {stats.autoGenerated}
              </div>
              <div className="unified-stat-label">Auto Generated</div>
            </div>
          </div>
        </div>
      </div>

      {/* Filters */}
      <div className="unified-section">
        <div className="unified-content-card unified-fade-in">
          <div className="unified-content-header">
            <BuildIcon sx={{ mr: 1 }} />
            <div className="unified-content-title">Filters & Search</div>
          </div>
          <div className="unified-content-body">
            <div className="unified-grid unified-grid-3">
              <TextField
                fullWidth
                size="small"
                label="Search Story Threads"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                InputProps={{
                  startAdornment: (
                    <InputAdornment position="start">
                      <SearchIcon />
                    </InputAdornment>
                  ),
                }}
                className="unified-input"
              />

              <FormControl fullWidth size="small">
                <InputLabel>Status</InputLabel>
                <Select
                  value={filterStatus}
                  label="Status"
                  onChange={(e) => setFilterStatus(e.target.value)}
                >
                  <MenuItem value="">All Statuses</MenuItem>
                  <MenuItem value="active">Active</MenuItem>
                  <MenuItem value="inactive">Inactive</MenuItem>
                  <MenuItem value="archived">Archived</MenuItem>
                </Select>
              </FormControl>

              <Box display="flex" alignItems="center">
                <Typography variant="body2" color="text.secondary">
                  Showing {filteredThreads.length} of {storyThreads.length} threads
                </Typography>
              </Box>
            </div>
          </div>
        </div>
      </div>

      {/* Story Threads */}
      <div className="unified-section">
        <div className="unified-content-card unified-fade-in">
          <div className="unified-content-header">
            <TimelineIcon sx={{ mr: 1 }} />
            <div className="unified-content-title">Story Threads</div>
          </div>
          <div className="unified-content-body">
            {filteredThreads.length > 0 ? (
              <div className="unified-grid unified-grid-2">
                {filteredThreads.map(renderThreadCard)}
              </div>
            ) : (
              <div className="unified-content-text">
                {storyThreads.length === 0 
                  ? 'No story threads created yet. Create your first story thread to start tracking news stories.'
                  : 'No story threads match your current filters. Try adjusting your search criteria.'
                }
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Thread Details Dialog */}
      <Dialog 
        open={showThreadDialog} 
        onClose={handleCloseDialog}
        maxWidth="md"
        fullWidth
      >
        <DialogTitle>
          {selectedThread?.title || 'Story Thread Details'}
        </DialogTitle>
        <DialogContent>
          {selectedThread && (
            <StoryThreadManager 
              threadId={selectedThread.id}
              onClose={handleCloseDialog}
            />
          )}
        </DialogContent>
        <DialogActions>
          <Button onClick={handleCloseDialog}>Close</Button>
        </DialogActions>
      </Dialog>

      {/* Create Thread Dialog */}
      <Dialog 
        open={showCreateDialog} 
        onClose={handleCloseCreateDialog}
        maxWidth="sm"
        fullWidth
      >
        <DialogTitle>Create New Story Thread</DialogTitle>
        <DialogContent>
          <StoryThreadManager 
            onClose={handleCloseCreateDialog}
            onSuccess={() => {
              handleCloseCreateDialog();
              loadStoryThreads();
            }}
          />
        </DialogContent>
        <DialogActions>
          <Button onClick={handleCloseCreateDialog}>Cancel</Button>
        </DialogActions>
      </Dialog>
    </div>
  );
};

export default UnifiedStoryDossiers;
